// Package compiler_test -- wrapper-runner RBAC generation contract tests.
//
// These tests verify that the compiler enable subcommand generates the
// wrapper-runner Role with the correct infrastructure.ontai.dev API groups.
// Regression guard for T-2B-9: prevents stale infra.ontai.dev or
// runner.ontai.dev groups from reappearing in the generated RBAC.
//
// INV-004: Guardian owns all RBAC. This Role is generated by the compiler
// as a bootstrap artifact. The tests verify the API group contract only --
// they do not test live cluster RBAC enforcement.
package compiler_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// buildCompiler builds the compiler binary into a temp directory and returns
// its path. Skips the test if the build fails (CI environment without Go).
func buildCompiler(t *testing.T) string {
	t.Helper()
	bin := filepath.Join(t.TempDir(), "compiler")
	cmd := exec.Command("go", "build", "-o", bin, "github.com/ontai-dev/conductor/cmd/compiler")
	cmd.Dir = repoRoot(t)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Skipf("compiler build failed (skipping — may be CI without full module graph): %v\n%s", err, out)
	}
	return bin
}

// repoRoot returns the conductor module root by walking up from the test file.
func repoRoot(t *testing.T) string {
	t.Helper()
	// The test lives at conductor/test/unit/compiler/; conductor/ is three levels up.
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	// Walk up until we find go.mod for the conductor module.
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("could not locate conductor go.mod")
		}
		dir = parent
	}
}

// runEnableWithClusterName runs `compiler enable --cluster-name <name> --output <dir>`
// and returns the path to the generated wrapper-runner.yaml in 05-post-bootstrap/.
func runEnableWithClusterName(t *testing.T, bin, clusterName string) string {
	t.Helper()
	out := t.TempDir()
	cmd := exec.Command(bin, "enable",
		"--cluster-name", clusterName,
		"--output", out,
	)
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("compiler enable failed: %v\n%s", err, output)
	}
	return filepath.Join(out, "05-post-bootstrap", "wrapper-runner.yaml")
}

// TestWrapperRunnerRole_UsesInfrastructureOntaiDevGroup verifies that the
// generated wrapper-runner Role grants access under infrastructure.ontai.dev,
// not the pre-migration infra.ontai.dev group. T-2B-9 regression guard.
func TestWrapperRunnerRole_UsesInfrastructureOntaiDevGroup(t *testing.T) {
	bin := buildCompiler(t)
	yamlPath := runEnableWithClusterName(t, bin, "ccs-mgmt")

	raw, err := os.ReadFile(yamlPath)
	if err != nil {
		t.Fatalf("read wrapper-runner.yaml: %v", err)
	}
	content := string(raw)

	if strings.Contains(content, "infra.ontai.dev") {
		t.Errorf("wrapper-runner.yaml contains stale 'infra.ontai.dev' group; must use 'infrastructure.ontai.dev'")
	}
	if strings.Contains(content, "runner.ontai.dev") {
		t.Errorf("wrapper-runner.yaml contains stale 'runner.ontai.dev' group; must use 'infrastructure.ontai.dev'")
	}
}

// TestWrapperRunnerRole_GrantsPackExecutionListWatch verifies that the Role
// grants get/list/watch on infrastructurepackexecutions.infrastructure.ontai.dev.
// This is required for the conductor execute Job to locate its own PackExecution.
func TestWrapperRunnerRole_GrantsPackExecutionListWatch(t *testing.T) {
	bin := buildCompiler(t)
	yamlPath := runEnableWithClusterName(t, bin, "ccs-mgmt")

	raw, err := os.ReadFile(yamlPath)
	if err != nil {
		t.Fatalf("read wrapper-runner.yaml: %v", err)
	}
	content := string(raw)

	if !strings.Contains(content, "infrastructurepackexecutions") {
		t.Errorf("wrapper-runner.yaml missing 'infrastructurepackexecutions' resource grant")
	}
}

// TestWrapperRunnerRole_GrantsRunnerConfigPatchUpdate verifies that the Role
// grants get/list/watch/patch/update on infrastructurerunnerconfigs.infrastructure.ontai.dev.
// The conductor execute Job must be able to update RunnerConfig status.
func TestWrapperRunnerRole_GrantsRunnerConfigPatchUpdate(t *testing.T) {
	bin := buildCompiler(t)
	yamlPath := runEnableWithClusterName(t, bin, "ccs-mgmt")

	raw, err := os.ReadFile(yamlPath)
	if err != nil {
		t.Fatalf("read wrapper-runner.yaml: %v", err)
	}
	content := string(raw)

	if !strings.Contains(content, "infrastructurerunnerconfigs") {
		t.Errorf("wrapper-runner.yaml missing 'infrastructurerunnerconfigs' resource grant")
	}
}

// TestWrapperRunnerRole_GrantsPackOperationResultWrite verifies the Role
// grants create/update/patch on packoperationresults.infrastructure.ontai.dev.
// The conductor execute Job writes PackOperationResult as its outcome channel.
func TestWrapperRunnerRole_GrantsPackOperationResultWrite(t *testing.T) {
	bin := buildCompiler(t)
	yamlPath := runEnableWithClusterName(t, bin, "ccs-mgmt")

	raw, err := os.ReadFile(yamlPath)
	if err != nil {
		t.Fatalf("read wrapper-runner.yaml: %v", err)
	}
	content := string(raw)

	if !strings.Contains(content, "packoperationresults") {
		t.Errorf("wrapper-runner.yaml missing 'packoperationresults' resource grant")
	}
}

// TestWrapperRunnerRole_NamespacedToCluster verifies that the generated
// Role and RoleBinding are scoped to seam-tenant-{clusterName}.
func TestWrapperRunnerRole_NamespacedToCluster(t *testing.T) {
	const clusterName = "ccs-test"
	bin := buildCompiler(t)
	yamlPath := runEnableWithClusterName(t, bin, clusterName)

	raw, err := os.ReadFile(yamlPath)
	if err != nil {
		t.Fatalf("read wrapper-runner.yaml: %v", err)
	}
	content := string(raw)

	expectedNS := "seam-tenant-" + clusterName
	if !strings.Contains(content, expectedNS) {
		t.Errorf("wrapper-runner.yaml does not contain expected namespace %q", expectedNS)
	}
}

// TestWrapperRunnerRole_NotGeneratedWithoutClusterName verifies that wrapper-runner.yaml
// is NOT generated when --cluster-name is absent. The file is cluster-specific
// and must not appear in a generic enable bundle.
func TestWrapperRunnerRole_NotGeneratedWithoutClusterName(t *testing.T) {
	bin := buildCompiler(t)
	out := t.TempDir()
	cmd := exec.Command(bin, "enable", "--output", out)
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("compiler enable failed: %v\n%s", err, output)
	}

	path := filepath.Join(out, "05-post-bootstrap", "wrapper-runner.yaml")
	if _, err := os.Stat(path); err == nil {
		t.Errorf("wrapper-runner.yaml was generated without --cluster-name; must not be present")
	}
}
