// compile_launch.go implements the `compiler launch` subcommand.
//
// Produces a single crds.yaml bundle containing all CRD YAML for every Seam
// operator. The bundle is assembled from embedded CRD files in each operator's
// config/crd/ directory. Output only — never applies resources to any cluster.
//
// conductor-schema.md §9 Step 2 (Management Cluster Bootstrap Sequence).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"

	conductorcrd "github.com/ontai-dev/conductor/config/crd"
	guardiancrd "github.com/ontai-dev/guardian/config/crd"
	platformcrd "github.com/ontai-dev/platform/config/crd"
	seamcorecrd "github.com/ontai-dev/seam-core/config/crd"
	wrappercrd "github.com/ontai-dev/wrapper/config/crd"
)

// runLaunchSubcommand parses launch-specific flags and calls compileLaunchBundle.
// conductor-schema.md §9 Step 2.
func runLaunchSubcommand(args []string) {
	fs := flag.NewFlagSet("launch", flag.ExitOnError)
	output := fs.String("output", "", "Output directory for crds.yaml (required)")
	_ = fs.String("kubeconfig", "", "Path to kubeconfig (unused in output-only mode; reserved for future validation)")

	if err := fs.Parse(args); err != nil {
		fmt.Fprintf(os.Stderr, "compiler launch: flag error: %v\n", err)
		os.Exit(1)
	}
	if *output == "" {
		fmt.Fprintln(os.Stderr, "compiler launch: --output is required")
		fs.Usage()
		os.Exit(1)
	}

	if err := compileLaunchBundle(*output); err != nil {
		fmt.Fprintf(os.Stderr, "compiler launch: %v\n", err)
		os.Exit(1)
	}
}

// compileLaunchBundle assembles the CRD manifest bundle from all Seam operators
// and writes it to {output}/crds.yaml as a single multi-document YAML file.
//
// CRD sources (all embedded at build time):
//   - platform.ontai.dev: TalosCluster, day-2 CRDs, SeamInfrastructureCluster/Machine
//   - security.ontai.dev: RBACPolicy, RBACProfile, IdentityBinding, IdentityProvider, PermissionSet
//   - infra.ontai.dev: ClusterPack, PackExecution, PackInstance
//   - infrastructure.ontai.dev: InfrastructureLineageIndex
//   - runner.ontai.dev: RunnerConfig
//
// Output is deterministic: CRD files within each operator are sorted by name.
// conductor-schema.md §9 Step 2.
func compileLaunchBundle(output string) error {
	if err := os.MkdirAll(output, 0755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	// Collect CRD YAML from all operator embedded filesystems.
	// Order: platform, guardian, wrapper, seam-core, conductor.
	sources := []struct {
		name string
		fsys fs.FS
	}{
		{"platform", platformcrd.FS},
		{"guardian", guardiancrd.FS},
		{"wrapper", wrappercrd.FS},
		{"seam-core", seamcorecrd.FS},
		{"conductor", conductorcrd.FS},
	}

	var bundle bytes.Buffer
	bundle.WriteString("# Seam Platform CRD Bundle\n")
	bundle.WriteString("# Generated by: compiler launch\n")
	bundle.WriteString("# Apply with: kubectl apply -f crds.yaml\n")
	bundle.WriteString("# conductor-schema.md §9 Step 2\n")

	for _, src := range sources {
		files, err := collectYAMLFiles(src.fsys)
		if err != nil {
			return fmt.Errorf("list CRD files for %s: %w", src.name, err)
		}
		sort.Strings(files)

		for _, name := range files {
			data, err := fs.ReadFile(src.fsys, name)
			if err != nil {
				return fmt.Errorf("read CRD %s/%s: %w", src.name, name, err)
			}
			bundle.WriteString("---\n")
			bundle.Write(data)
			if len(data) > 0 && data[len(data)-1] != '\n' {
				bundle.WriteByte('\n')
			}
		}
	}

	outPath := filepath.Join(output, "crds.yaml")
	if err := os.WriteFile(outPath, bundle.Bytes(), 0644); err != nil {
		return fmt.Errorf("write crds.yaml: %w", err)
	}
	return nil
}

// collectYAMLFiles returns all *.yaml filenames in the root of the embedded FS.
func collectYAMLFiles(fsys fs.FS) ([]string, error) {
	entries, err := fs.ReadDir(fsys, ".")
	if err != nil {
		return nil, err
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() && filepath.Ext(e.Name()) == ".yaml" {
			names = append(names, e.Name())
		}
	}
	return names, nil
}
